"""Persistence for reviewer accounts, sessions, cases, and the audit log.

SQLite is used by default (local development and tests). Setting
``DATABASE_URL`` to a PostgreSQL connection string switches the whole layer
to PostgreSQL (Render's managed database) without touching any route code:
placeholders stay ``?`` and are translated on the fly.

Security properties:

- Session tokens are never stored raw; only an HMAC keyed with
  YONKO_SESSION_SECRET reaches the database (see app.security).
- Sessions carry an expiry (SESSION_TTL_HOURS) and expired rows are
  removed opportunistically.
- Every security-relevant event lands in the audit_log table so reviewers
  can show judges a tamper-evident trail of sign-ins and analyses.
"""

from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path

DEFAULT_DB_PATH = Path(__file__).resolve().parents[1] / "data" / "samanvay.sqlite"

_SESSIONS_DDL = """
    CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        created_at TEXT NOT NULL,
        expires_at TEXT NOT NULL,
        FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE
    );
"""

_AUDIT_DDL_SQLITE = """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        event TEXT NOT NULL,
        email TEXT NOT NULL DEFAULT '',
        ip TEXT NOT NULL DEFAULT '',
        detail TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL
    );
"""

_AUDIT_DDL_PG = """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event TEXT NOT NULL,
        email TEXT NOT NULL DEFAULT '',
        ip TEXT NOT NULL DEFAULT '',
        detail TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL
    );
"""


def db_path() -> Path:
    override = os.getenv("SAMANVAY_DB_PATH")
    return Path(override) if override else DEFAULT_DB_PATH


def database_url() -> str:
    return os.getenv("DATABASE_URL", "").strip()


def _init_sqlite(connection: sqlite3.Connection) -> None:
    connection.execute("PRAGMA foreign_keys = ON")
    # Migrate pre-security databases: the old sessions table stored raw
    # tokens. Sessions are disposable, so the safe migration is recreate.
    row = connection.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'sessions'"
    ).fetchone()
    if row is not None:
        columns = {
            info[1]
            for info in connection.execute("PRAGMA table_info(sessions)").fetchall()
        }
        if "token_hash" not in columns:
            connection.execute("DROP TABLE sessions")
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS users (
            email TEXT PRIMARY KEY,
            password_hash TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            dob TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );
        """
        + _SESSIONS_DDL
        + """
        CREATE TABLE IF NOT EXISTS cases (
            id TEXT NOT NULL,
            owner_email TEXT NOT NULL,
            payload TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (id, owner_email),
            FOREIGN KEY (owner_email) REFERENCES users(email) ON DELETE CASCADE
        );
        """
        + _AUDIT_DDL_SQLITE
    )


def _init_postgres(connection) -> None:
    statements = (
        """
        CREATE TABLE IF NOT EXISTS users (
            email TEXT PRIMARY KEY,
            password_hash TEXT NOT NULL,
            name TEXT NOT NULL DEFAULT '',
            dob TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );
        """,
        _SESSIONS_DDL,
        """
        CREATE TABLE IF NOT EXISTS cases (
            id TEXT NOT NULL,
            owner_email TEXT NOT NULL,
            payload TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (id, owner_email),
            FOREIGN KEY (owner_email) REFERENCES users(email) ON DELETE CASCADE
        );
        """,
        _AUDIT_DDL_PG,
    )
    with connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


class _PostgresShim:
    """Exposes the sqlite3-style execute interface used across the app.

    Translates ``?`` placeholders to ``%s`` so route code stays backend
    agnostic. psycopg rows are dict-like, matching sqlite3.Row access.
    """

    def __init__(self, connection) -> None:
        self._connection = connection

    def execute(self, sql: str, params: tuple = ()):  # noqa: A002 - sqlite parity
        return self._connection.execute(sql.replace("?", "%s"), params)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()


@contextmanager
def get_connection():
    url = database_url()
    if url:
        import psycopg
        from psycopg.rows import dict_row

        # Render hands out postgres:// URLs; psycopg requires postgresql://.
        if url.startswith("postgres://"):
            url = "postgresql://" + url[len("postgres://"):]
        connection = psycopg.connect(url, row_factory=dict_row)
        try:
            _init_postgres(connection)
            yield _PostgresShim(connection)
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()
        return

    path = db_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    try:
        _init_sqlite(connection)
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def record_audit(event: str, email: str = "", ip: str = "", detail: str = "") -> None:
    """Append one security event to the audit log.

    Never pass passwords, tokens, or document contents as ``detail``.
    Failures to write the log must not break the request being audited.
    """
    from app.security import utc_now

    try:
        with get_connection() as connection:
            connection.execute(
                """
                INSERT INTO audit_log (event, email, ip, detail, created_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (event, str(email or "")[:254], str(ip or "")[:64],
                 str(detail or "")[:500], utc_now()),
            )
    except Exception:
        pass
